// <auto-generated />
using System;
using HaveASeat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HaveASeat.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250510083457_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HaveASeat.Models.Abbonamento", b =>
                {
                    b.Property<Guid>("AbbonamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durata")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prezzo")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("AbbonamentoId");

                    b.ToTable("Abbonamento");
                });

            modelBuilder.Entity("HaveASeat.Models.Appuntamento", b =>
                {
                    b.Property<Guid>("AppuntamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OraFine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OraInizio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SaloneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SaloneId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SlotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SlotId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.HasKey("AppuntamentoId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("SaloneId");

                    b.HasIndex("SaloneId1");

                    b.HasIndex("SlotId");

                    b.HasIndex("SlotId1");

                    b.ToTable("Appuntamento");
                });

            modelBuilder.Entity("HaveASeat.Models.Immagine", b =>
                {
                    b.Property<Guid>("ImmagineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Percorso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SaloneId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ImmagineId");

                    b.HasIndex("SaloneId");

                    b.ToTable("Immagine");
                });

            modelBuilder.Entity("HaveASeat.Models.Orario", b =>
                {
                    b.Property<Guid>("OrarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("Apertura")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("Chiusura")
                        .HasColumnType("time");

                    b.Property<string>("Giorno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SaloneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SaloneId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrarioId");

                    b.HasIndex("SaloneId");

                    b.HasIndex("SaloneId1");

                    b.ToTable("Orario");
                });

            modelBuilder.Entity("HaveASeat.Models.Recensione", b =>
                {
                    b.Property<Guid>("RecensioneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Commento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SaloneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SaloneId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Voto")
                        .HasColumnType("int");

                    b.HasKey("RecensioneId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("SaloneId");

                    b.HasIndex("SaloneId1");

                    b.ToTable("Recensione");
                });

            modelBuilder.Entity("HaveASeat.Models.Salone", b =>
                {
                    b.Property<Guid>("SaloneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CAP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Citta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Regione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SitoWeb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SaloneId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Salone");
                });

            modelBuilder.Entity("HaveASeat.Models.SaloneAbbonamento", b =>
                {
                    b.Property<Guid>("SaloneAbbonamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AbbonamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsTrial")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SaloneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SaloneId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SaloneAbbonamentoId");

                    b.HasIndex("AbbonamentoId");

                    b.HasIndex("SaloneId");

                    b.HasIndex("SaloneId1");

                    b.ToTable("SaloneAbbonamento");
                });

            modelBuilder.Entity("HaveASeat.Models.SaloneResponsabile", b =>
                {
                    b.Property<Guid>("SaloneResponsabileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SaloneId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SaloneResponsabileId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("SaloneId");

                    b.ToTable("SaloneResponsabile");
                });

            modelBuilder.Entity("HaveASeat.Models.SaloneServizio", b =>
                {
                    b.Property<Guid>("SaloneServizioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SaloneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServizioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SaloneServizioId");

                    b.HasIndex("SaloneId");

                    b.HasIndex("ServizioId");

                    b.ToTable("SaloneServizio");
                });

            modelBuilder.Entity("HaveASeat.Models.Servizio", b =>
                {
                    b.Property<Guid>("ServizioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Durata")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prezzo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid?>("SaloneId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ServizioId");

                    b.HasIndex("SaloneId");

                    b.ToTable("Servizio");
                });

            modelBuilder.Entity("HaveASeat.Models.Slot", b =>
                {
                    b.Property<Guid>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OraFine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OraInizio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SaloneId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SlotId");

                    b.HasIndex("SaloneId");

                    b.ToTable("Slot");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.ApplicationUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.ApplicationUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.ApplicationUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.ApplicationUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HaveASeat.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.ApplicationUser");

                    b.Property<bool>("Azienda")
                        .HasColumnType("bit");

                    b.Property<string>("CAP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Città")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodiceFiscale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cognome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataRegistrazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartitaIVA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RagioneSociale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDI")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("HaveASeat.Models.Appuntamento", b =>
                {
                    b.HasOne("HaveASeat.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HaveASeat.Models.Salone", "Salone")
                        .WithMany()
                        .HasForeignKey("SaloneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HaveASeat.Models.Salone", null)
                        .WithMany("Appuntamenti")
                        .HasForeignKey("SaloneId1");

                    b.HasOne("HaveASeat.Models.Slot", "Slot")
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HaveASeat.Models.Slot", null)
                        .WithMany("Appuntamenti")
                        .HasForeignKey("SlotId1");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Salone");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("HaveASeat.Models.Immagine", b =>
                {
                    b.HasOne("HaveASeat.Models.Salone", "Salone")
                        .WithMany()
                        .HasForeignKey("SaloneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Salone");
                });

            modelBuilder.Entity("HaveASeat.Models.Orario", b =>
                {
                    b.HasOne("HaveASeat.Models.Salone", "Salone")
                        .WithMany()
                        .HasForeignKey("SaloneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HaveASeat.Models.Salone", null)
                        .WithMany("Orari")
                        .HasForeignKey("SaloneId1");

                    b.Navigation("Salone");
                });

            modelBuilder.Entity("HaveASeat.Models.Recensione", b =>
                {
                    b.HasOne("HaveASeat.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HaveASeat.Models.Salone", "Salone")
                        .WithMany()
                        .HasForeignKey("SaloneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HaveASeat.Models.Salone", null)
                        .WithMany("Recensioni")
                        .HasForeignKey("SaloneId1");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Salone");
                });

            modelBuilder.Entity("HaveASeat.Models.Salone", b =>
                {
                    b.HasOne("HaveASeat.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Saloni")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("HaveASeat.Models.SaloneAbbonamento", b =>
                {
                    b.HasOne("HaveASeat.Models.Abbonamento", "Abbonamento")
                        .WithMany()
                        .HasForeignKey("AbbonamentoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HaveASeat.Models.Salone", "Salone")
                        .WithMany()
                        .HasForeignKey("SaloneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HaveASeat.Models.Salone", null)
                        .WithMany("SaloneAbbonamenti")
                        .HasForeignKey("SaloneId1");

                    b.Navigation("Abbonamento");

                    b.Navigation("Salone");
                });

            modelBuilder.Entity("HaveASeat.Models.SaloneResponsabile", b =>
                {
                    b.HasOne("HaveASeat.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HaveASeat.Models.Salone", "Salone")
                        .WithMany()
                        .HasForeignKey("SaloneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Salone");
                });

            modelBuilder.Entity("HaveASeat.Models.SaloneServizio", b =>
                {
                    b.HasOne("HaveASeat.Models.Salone", "Salone")
                        .WithMany()
                        .HasForeignKey("SaloneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HaveASeat.Models.Servizio", "Servizio")
                        .WithMany()
                        .HasForeignKey("ServizioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Salone");

                    b.Navigation("Servizio");
                });

            modelBuilder.Entity("HaveASeat.Models.Servizio", b =>
                {
                    b.HasOne("HaveASeat.Models.Salone", null)
                        .WithMany("Servizi")
                        .HasForeignKey("SaloneId");
                });

            modelBuilder.Entity("HaveASeat.Models.Slot", b =>
                {
                    b.HasOne("HaveASeat.Models.Salone", "Salone")
                        .WithMany()
                        .HasForeignKey("SaloneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Salone");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.ApplicationUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.ApplicationUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.ApplicationUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.ApplicationUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HaveASeat.Models.Salone", b =>
                {
                    b.Navigation("Appuntamenti");

                    b.Navigation("Orari");

                    b.Navigation("Recensioni");

                    b.Navigation("SaloneAbbonamenti");

                    b.Navigation("Servizi");
                });

            modelBuilder.Entity("HaveASeat.Models.Slot", b =>
                {
                    b.Navigation("Appuntamenti");
                });

            modelBuilder.Entity("HaveASeat.Models.ApplicationUser", b =>
                {
                    b.Navigation("Saloni");
                });
#pragma warning restore 612, 618
        }
    }
}
